Hackfix to disable fastmem rewrite feature, works around segfault problem on ludo
piepacker/duckstation pull request #10
Opened 2021-05-29 22:15 UTC by jstine35

It should be better to uncover the reason why ludo (golang, more likely) is interfering with the PageFault/SegFault handler on Windows.

2021-05-30 05:43 UTC, kivutar requested changes
Can we do it this way instead?

https://github.com/libretro/swanstation/commit/f637330e3bac63d3f8fb7018bfd3249d1180faa8

2021-05-30 13:22 UTC, jstine35 commented
If it works, probably, yes.  I didn't check Duckstation internals, but usually mmap modes offer nice perf boosts on DMAs and other things outside of dynarec. Or in other words, mmap mode should have lots of features in addition to just this tiny dynarec optimization. But the description makes it sound like it's just this feature.

In any case, even LUT is probably fine for perf? Even a proper robust mmap feature is something that makes sense for PS2, GC, Wii. For PS1 it'll improve perf of maybe MPEG video playback and not much else.

So yeah, it's fine to just configure it to use LUT I think.

(also at a glance I think mmap is not stable yet - the rewrite logic seems to be missing some edge cases, which might explain it breaking OpenBIOS)

2021-05-30 14:08 UTC, kivutar commented
Stenzek was saying that the perf gain over LUT was 15%.

I think we can live with having the default to LUT, and switch to fastmem on the platforms where it works.

2021-05-30 14:14 UTC, kivutar commented
Added this instead https://github.com/piepacker/swanstation/pull/11

2021-05-30 14:14 UTC, closed without merging

2021-05-30 23:54 UTC, jstine35 commented
15% is still like only 0.005ms on my tests. The dynarec is using between 0.05 and 0.1ms in most games.

15% could matter when you want to run advanced run-ahead or GGPO... _maybe_.. :)

2021-05-31 04:30 UTC, kivutar commented
I hope somebody will find a fix for fastmem.
Meanwhile, we don't completely disable the feature, we just change the default value of the setting.
Users on Linux and OSX can switch back to fastmem easily.